apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/cert/ca.pem
    server: https://192.168.1.5:6443
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/cert/server.pem 
    client-key: /etc/kubernetes/cert/server-key.pem
